### ISSUE TITLE
add Markdown support

### ISSUE THREAD

**Issue by pbelokon** [bryce-seefieldt/ez-txt2html#4]
## Description 

I'd like to incorporate Markdown file parsing into your project. What I will do is utilize regular expressions that will transform the following Markdown elements [Italics, Bold, Heading 1, Heading 2, or a Link](https://commonmark.org/help/)  into their respective HTML counterparts and then send them to the ``convertTextContent(parsedLines, filename)`` function.

**Comment by bryce-seefieldt** [comment]
Well done, thanks.

**Comment by bryce-seefieldt** [comment]
Well done, thanks
